const _colors = {
  black: 'var(--black)',
  blue: 'var(--blue)',
  blueDark: 'var(--blueDark)',
  blueLight: 'var(--blueLight)',
  bronze: 'var(--bronze)',
  brown: 'var(--brown)',
  brownDark: 'var(--brownDark)',
  brownLight: 'var(--brownLight)',
  brownLightOver: 'var(--brownLightOver)',
  brownVeryLight: 'var(--brownVeryLight)',
  gray: 'var(--gray)',
  grayBrown: 'var(--grayBrown)',
  grayBrownDark: 'var(--grayBrownDark)',
  grayBrownLight: 'var(--grayBrownLight)',
  grayDark: 'var(--grayDark)',
  grayLight: 'var(--grayLight)',
  grayMedium: 'var(--grayMedium)',
  green: 'var(--green)',
  greenSea: 'var(--greenSea)',
  orange: 'var(--orange)',
  orangeRgb: 'var(--orangeRgb)',
  pink: 'var(--pink)',
  purpleDark: 'var(--purpleDark)',
  red: 'var(--red)',
  white: 'var(--white)',
  xanadu: 'var(--xanadu)',
  yellow: 'var(--yellow)',
  yellowDark: 'var(--yellowDark)',
  yellowRgb: 'var(--yellowRgb)',
};

export const themes = {
  fonts: {
    titles: 'var(--fontStyles)',
    others: 'var(--fontStyles)',
  },
  grid: {
    maxWidth: '68em',
  },
  palette: {
    breadcrumb: {
      color: 'var(--textBreadcrumb)',
      homeColor: 'var(--links)',
    },
    categories: {
      'Back-End': _colors.xanadu,
      'CSS': _colors.blueLight,
      'DevOps': _colors.green,
      'Eventos': _colors.blue,
      'Git': _colors.black,
      'JavaScript': _colors.yellow,
      'Portfólio': _colors.bronze,
      'Publicações': _colors.pink,
      'Shots': _colors.orange,
      'Tecnologia': _colors.purpleDark,
      'UX, UI e AI': _colors.greenSea,
      'Webstandards': _colors.red,
    },
    general: {
      bg: 'var(--bg)',
      bgTransition: _colors.grayLight,
      borders: _colors.grayMedium,
      boxShadows: _colors.grayMedium,
      color: 'var(--textColor)',
      links: 'var(--links)',
      negativeColor: _colors.white,
      textShadows: _colors.grayDark,
    },
    pagination: {
      active: _colors.orange,
      bgWrap: _colors.brownVeryLight,
      bgHoverLinks: _colors.grayBrown,
      borderLightLinks: _colors.grayBrownLight,
      borderDarkLinks: _colors.grayBrownDark,
      bordersWrap: _colors.brown,
      text: _colors.brownDark,
    },
    posts: {
      bgCredits: _colors.white,
      blockquoteBg: _colors.white,
      blockquoteBorder: _colors.green,
      borderInfos: _colors.grayLight,
      description: _colors.gray,
      links: 'var(--links)',
      linksBorder: 'var(--linksBorder)',
      shadowCredits: _colors.grayMedium,
    },
    postList: {
      bgCategories: _colors.orange,
      bgContent: _colors.grayLight,
      readMore: _colors.green,
      text: 'var(--textThumbs)',
    },
    about: {
      firstBorder: _colors.orangeRgb,
      secondBorder: _colors.yellowRgb,
      titleBorder: _colors.yellow,
      titleBorderBefore: _colors.yellowDark,
    },
    sidebar: {
      bg: 'var(--bgSidebar)',
      bgLinkHover: 'var(--bg)',
      links: 'var(--links)',
      linksHover: 'var(--sidebarLinksHover)',
      name: 'var(--text)',
    },
  },
};
